[options]
addons_path = /home/hieunqdev/odoo18_tutor/addons, /home/hieunqdev/odoo18_tutor/custom_addons
admin_passwd = $pbkdf2-sha512$600000$QWitdS7l3BtDSGnNuZdSSg$SpruMJsWwQGXkhH7Td18JsIVVoV4PPCKHd9MGM1H0rGzKP7yZJNDt5pCziGh0vR.WN6Ot6NqgqHgnrPRp94rjg
db_host = localhost
db_user = hieunqdev
db_port = 5432
db_password = 1
http_port = 8069

